### PR TITLE
 Updated for 9.0.2

### PR DESCRIPTION
**Pull request by Kautzman**

### CODE REVIEW

**Comment by Kautzman** [comment]
9.0.2 updates along side some minor de-obfuscation

**Comment by mklemarczyk** [comment]
Change reviewed, addon loads and game plays well.

I would suggest to change default position of the game next to minimap. It is hard to press button that is hidden under another button.
There is a problem with image of close button, the red icon is not displayed.

**Comment by Kautzman** [comment]
Good notes!

There is definitely some polish work that could be done yet.  I'd like to do another pass in a couple weeks when the initial launch excitement settles a bit.

**Comment by beren12** [comment]
Looks like most of these changes are also required for tbc classic, esp. the backdrop mixin.

**Pull request merged**
